### ISSUE TITLE
Determine the user flow and additional features

### ISSUE THREAD

**Issue by asethi98** [asethi98/emoji-checker#1]

**Comment by asethi98** [comment]
Hi @thunderStormGS ! Here are the sample Android screens I used in our first presentation. Feel free to modify them and add more screens. See the attached word doc. 
[Emoji Checker UI.docx](https://github.com/asethi98/emoji-checker/files/2398327/Emoji.Checker.UI.docx)

**Comment by thunderStormGS** [comment]
Awesome! Thank you @asethi98 !
