### ISSUE TITLE
Determine How to Record and Format User Data

### ISSUE THREAD

**Issue by asethi98** [asethi98/emoji-checker#21]
-Determine how to record the user data from the app (Create an Account, Query screens) via JSON by discussing with the back-end team
-Determine how the data will be read from the database to display the user's previous emojis

**Comment by thunderStormGS** [comment]
https://www.getpostman.com/

https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop?hl=en

An API development tool to assist in formatting and testing the screens in Android Studio.

**Comment by thunderStormGS** [comment]
[RecUserData.txt](https://github.com/asethi98/emoji-checker/files/2476993/RecUserData.txt)

**Comment by thunderStormGS** [comment]
[ReadEmojisFromDB.txt](https://github.com/asethi98/emoji-checker/files/2476994/ReadEmojisFromDB.txt)
