### ISSUE TITLE
Learn How the Data will be Displayed on the View Previous Emojis Screen

### ISSUE THREAD

**Issue by asethi98** [asethi98/emoji-checker#23]
-Determine how the data will be read from the database to display the user's previous emojis by collaborating with the back-end team

**Comment by thunderStormGS** [comment]
[DisplayPrevEmojis.txt](https://github.com/asethi98/emoji-checker/files/2474155/DisplayPrevEmojis.txt)

Results of a conversation w/ a member of the back-end team to determine how such data would be display for previous user input.
