### ISSUE TITLE
Start setting up the 'Query/Select an Emoji' screen on Android Studio 

### ISSUE THREAD

**Issue by asethi98** [asethi98/emoji-checker#4]

**Comment by Jocelyn-lopez** [comment]
![screen](https://user-images.githubusercontent.com/42979886/45988970-93390a00-c047-11e8-96c4-bc0d806c3f42.png)
![menu_bar](https://user-images.githubusercontent.com/42979886/45988973-98965480-c047-11e8-8ae8-14ecd6f97434.png)

**Comment by Jocelyn-lopez** [comment]
![query_screen](https://user-images.githubusercontent.com/42979886/45988983-a8ae3400-c047-11e8-931c-f7bc5fe1825e.png)
