### ISSUE TITLE
JUnit: Check if the Username and Password Entered by the User is correct

### ISSUE THREAD

**Issue by asethi98** [asethi98/emoji-checker#40]
-Write a test method that gives an error message if the username and password don’t match.
- This requires using the database set up by the back-end team. 
http://www.emoji-survey.me/auth/
username: phoneapp
password: dews798@mess

If you need to use the HTTP get method, these resources might help. 
- Scroll all the way to the bottom of this link: https://www.kompulsa.com/how-to-send-a-post-request-in-android/
- Watch the video to set up the Volley library and look at the built-in methods it generates.

**Comment by riyanimam** [comment]
@thunderStormGS 
-Use the Volley library in Android Studio. You'll have to use the HTTP Post method.

Scroll all the way to the bottom of this link:
https://www.kompulsa.com/how-to-send-a-post-request-in-android/
Watch the video to set up the Volley library and look at the built-in methods it generates.

**Comment by riyanimam** [comment]
Take a look at Issue #37.
