### ISSUE TITLE
Design the overall look and feel of the app

### ISSUE THREAD

**Issue by thunderStormGS** [asethi98/emoji-checker#9]

**Comment by thunderStormGS** [comment]
[Emoji Design Flow.pdf](https://github.com/asethi98/emoji-checker/files/2407181/Emoji.Design.Flow.pdf)

**Comment by thunderStormGS** [comment]
[Emoji Design-Flow.pdf](https://github.com/asethi98/emoji-checker/files/2408325/Emoji.Design-Flow.pdf)

**Comment by asethi98** [comment]
Updated UI
[Emoji Checker UI New.pdf](https://github.com/asethi98/emoji-checker/files/2409219/Emoji.Checker.UI.New.pdf)
